In [1]:
import numpy as np

# Numpy array

In [2]:
a_1 = np.array([[1, 2, 3, 4], 
               [1, 2, 3, 4]])
a_1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [3]:
print(type(a_1))
print(a_1.dtype)
print(a_1.shape)
print(a_1.ndim)
print(a_1.size)

<class 'numpy.ndarray'>
int32
(2, 4)
2
8


# Creating Numpy arrays from Scratch

### 'zeros', 'ones', 'full', 'arrange', 'linspace'

In [4]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
np.ones([2, 4], dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
np.arange(0, 20, 4)

array([ 0,  4,  8, 12, 16])

In [7]:
np.full([2, 4], 1) # ~ np.ones([2, 4])

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
np.linspace(1, 2, 9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

### 'random'

In [9]:
np.random.random(size = 3)

array([0.11687067, 0.75676208, 0.85964229])

In [10]:
np.random.randint(1, 10, [2, 4])

array([[2, 2, 5, 9],
       [5, 2, 9, 7]])

In [11]:
np.random.rand(2, 4)

array([[0.34719814, 0.54734853, 0.08825404, 0.92121024],
       [0.87231976, 0.6158398 , 0.36500534, 0.35528994]])

In [12]:
np.random.normal(size = 2)

array([ 0.41495675, -1.73942057])

# Array indexing and slicing


In [13]:
x = np.random.randint(0, 10, [2, 4])
x

array([[4, 8, 5, 3],
       [6, 2, 3, 8]])

In [14]:
x[1][3] = 100
x

array([[  4,   8,   5,   3],
       [  6,   2,   3, 100]])

In [15]:
# One-dimensional array (Done)
# Multi-dimensional array

# For instance, 2 rows and 2 columns
x[:2, 1:3]

array([[8, 5],
       [2, 3]])

# Reshaping Arrays and transpose

In [16]:
y = np.arange(1, 10, 1)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y.reshape(9, 1) #y.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Array concatenate and Splitting

In [18]:
x = np.ones([1, 5], dtype = int)
y = np.full([5, 1], 2)
print(x)
print(y)

[[1 1 1 1 1]]
[[2]
 [2]
 [2]
 [2]
 [2]]


In [19]:
x = x.reshape(5, 1)
np.concatenate((x, y), axis = 1)

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [20]:
x = np.random.random([2, 4])
x

array([[0.8066409 , 0.73272454, 0.28128941, 0.5698422 ],
       [0.79028041, 0.09403031, 0.93671949, 0.77702545]])

In [21]:
np.split(x, [1, 2])

[array([[0.8066409 , 0.73272454, 0.28128941, 0.5698422 ]]),
 array([[0.79028041, 0.09403031, 0.93671949, 0.77702545]]),
 array([], shape=(0, 4), dtype=float64)]

# Sorting arrays

# Sorting along the rows or columns

In [22]:
x = np.random.normal(size = 5)
print(x)
np.sort(x)

[-1.60551143 -0.51197042 -0.27764354  0.33704117  1.33167052]


array([-1.60551143, -0.51197042, -0.27764354,  0.33704117,  1.33167052])

In [23]:
y = np.argsort(x)
y

array([0, 1, 2, 3, 4], dtype=int64)

In [24]:
Mat_A = np.random.randint(1, 10, [4, 6])
Mat_A

array([[3, 2, 8, 3, 2, 6],
       [9, 8, 2, 4, 1, 9],
       [1, 2, 6, 3, 6, 8],
       [9, 3, 1, 1, 3, 9]])

In [25]:
np.sort(Mat_A, axis = 1)

array([[2, 2, 3, 3, 6, 8],
       [1, 2, 4, 8, 9, 9],
       [1, 2, 3, 6, 6, 8],
       [1, 1, 3, 3, 9, 9]])

# Linear algebra

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(A.dot(B))
print(A@B)

[[ 22  28]
 [ 49  64]
 [ 76 100]]
[[ 22  28]
 [ 49  64]
 [ 76 100]]


In [27]:
B.T.dot(A) # B.T@A

array([[48, 57, 66],
       [60, 72, 84]])

# Practicing example

In [28]:
# Number of foods sold

x = np.random.randint(1, 15, [6, 3])
x

array([[12,  9,  9],
       [13,  7,  8],
       [11,  4,  6],
       [11, 13, 10],
       [14, 13, 10],
       [14,  1,  2]])

In [35]:
# Create weekly_sells DataFrame

import pandas as pd

weekly_sells = pd.DataFrame(x, index = ["Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"], 
                            columns = ["Grilled chicken", "Sandwich", "Pizza"])
weekly_sells

Grilled chicken  Sandwich  Pizza
Mon                 12         9      9
Tues                13         7      8
Wed                 11         4      6
Thurs               11        13     10
Fri                 14        13     10
Sat                 14         1      2

In [54]:
# Create the price of each food DataFRame

y = np.random.randint(1, 10, [1, 3])
price = pd.DataFrame(y, index = ["Price"], columns = ["Grilled chicken", "Sandwich", "Pizza"])
price

Grilled chicken  Sandwich  Pizza
Price                3         9      1

# revenue of each day and total revenue of the week.

In [67]:
revenue_eachday = weekly_sells@price.T
revenue_eachday

Price
Mon      126
Tues     110
Wed       75
Thurs    160
Fri      169
Sat       53

In [68]:
weekly_sells["Price"] = revenue_eachday
weekly_sells

Grilled chicken  Sandwich  Pizza  Price
Mon                 12         9      9    126
Tues                13         7      8    110
Wed                 11         4      6     75
Thurs               11        13     10    160
Fri                 14        13     10    169
Sat                 14         1      2     53